Repository TomatoesBurner/Agile-Web-Community-Forum, pull requests merged in 2024-05, with the labels that each got.

#4 posts in homepage displays according to different task
  app/blueprints/postCom/postCom.py
  app/forms.py
  app/models.py
  app/templates/base.html
  app/templates/index.html
  app/templates/login.html
Labels: enhancement

#19 new branch Feature/post com page
  .flaskenv
  app/blueprints/auth/auth.py
  app/blueprints/postCom/postCom.py
  app/forms.py
  app/static/css/post-detail.css
  app/static/images/logo.png
  app/templates/login.html
  app/templates/post-detail.html
Labels: enhancement, frontend

#25 Change post-detail.html to inherit base.html schema
  app/static/css/login.css
  app/static/css/post-detail.css
  app/static/css/register.css
  app/templates/login.html
  app/templates/post-detail.html
  app/templates/register.html
Labels: frontend

#29 Bugfix: Lack of initiation file #22
  media/avatars/4a128ee6ddddcfffcc65c2e60f8dfe94_l.png
  media/avatars/6b87f626a48eac0cfdaf288216ef1c7e_l.png
  media/avatars/d4ea40a96f2938d7510e6b2289f31e28_l.png
Labels: bug

#37 Fix minor issues in post comments and enhance features
  app/__init__.py
  app/blueprints/auth/auth.py
  app/blueprints/postCom/postCom.py
  app/forms.py
  app/models.py
  app/templates/base.html
  app/templates/posts.html
  app/templates/register.html
  config.py
  run.py
Labels: bug, enhancement

#38 Enhance:post-detail.html
  app/static/css/post-detail.css
  app/static/css/posts.css
  app/static/css/profile.css
  app/static/js/post-detail.js
  app/templates/base.html
  app/templates/post-detail.html
  app/templates/profile.html
Labels: enhancement, frontend

#48 Bugfix/Collections
  app/forms.py
  app/models.py
  app/static/css/base.css
  app/static/css/index.css
  app/static/css/login.css
  app/static/css/post-detail.css
  app/static/css/posts.css
  app/static/css/profile.css
  app/static/js/index.js
  app/static/js/post-detail.js
  app/static/js/post.js
  app/templates/index.html
  app/templates/post-detail.html
  app/templates/posts.html
  app/templates/profile.html
Labels: bug

#57 Bugfix: Validation of files and bugfix
  README.md
  app/models.py
  app/static/css/base.css
  app/static/css/index.css
  app/static/css/login.css
  app/static/css/posts.css
  app/templates/base.html
  app/templates/forgot-password.html
  app/templates/index.html
  app/templates/login.html
  app/templates/post-detail.html
  app/templates/posts.html
  app/templates/profile.html
  app/templates/register.html
  app/templates/security-question.html
Labels: bug, documentation
